name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload app files to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_HOST }}
          username: azureuser
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "./*"
          target: "/home/azureuser/MyNodeAppProduction"

      - name: SSH and deploy container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: azureuser
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /home/azureuser/MyNodeAppProduction
            docker build -t mynodeapp .
            docker stop mynodeapp || true
            docker rm mynodeapp || true
            docker run -d -p 3000:3000 --name mynodeapp mynodeapp
